blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blogem import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogem.urls')),
    # path('logout/', views.logoutView, name='logout'),
]

blog/blogem/urls.py
from django.urls import path
from . import views
app_name = 'blogem'

urlpatterns = [
    path('register/', views.registerView, name='register'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),

    path('', views.HomeView.as_view(), name='home'),

    path('all/', views.PostsListView.as_view(), name='all_posts'),
    path('posts/new/', views.PostsCreateView.as_view(), name='create_post'),
    path('posts/<int:pk>/', views.PostsDetailView.as_view(), name='posts_detail'),
    path('posts/<int:pk>/delete/',
         views.PostsDeleteView.as_view(), name='delete_post'),
    path('posts/<int:pk>/update/',
         views.PostsUpdateView.as_view(), name='update_post'),
    path('posts/<int:pk>/comment', views.add_comment, name='create_comment'),
    # path('comment/<int:pk>/remove',
    #      views.remove_comment, name='delete_comment'),
]

blog/blogem/models.py
from django.db import models
from django.urls import reverse
# from django.utils.text import slugify
# Create your models here.


class Posts(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()

    def publish(self):
        self.save()

    def comments(self):
        return self.comments.all()

    def get_absolute_url(self):
        return reverse('blogem:posts_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Comments(models.Model):
    post = models.ForeignKey(
        'blogem.Posts', related_name='comments', on_delete=models.CASCADE)
    user = models.CharField(max_length=25)
    content = models.TextField()

    app_comment = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('blogem:post_list')

    def cmt_app(self):
        self.save()

    def __str__(self):
        return self.user

blog/blogem/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Posts, Comments


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class PostsForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ('user', 'title', 'content')


class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('user', 'content')

blog/blogem/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from .forms import UserCreateForm, PostsForm, CommentsForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import Posts, Comments
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.


class HomeView(TemplateView):
    template_name = 'blogem/home.html'


def registerView(request):
    form = UserCreateForm()

    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            # messages.success(request, 'Account was created for ' + user)
            return redirect('blogem:login')
    context = {'form': form}
    return render(request, 'accounts/register.html', context)


def loginView(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect('blogem:home')
            else:
                return HttpResponse("account not active")
        else:
            messages.warning(request, 'Username OR password is incorrect')

    return render(request, 'accounts/login.html')


@login_required
def logoutView(request):
    logout(request)
    return redirect('blogem:home')


class PostsListView(ListView):
    model = Posts

    def get_queryset(self):
        return Posts.objects.all()


class PostsDetailView(DetailView):
    model = Posts


class PostsCreateView(CreateView, LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name = 'blogem/posts_detail'
    form_class = PostsForm
    model = Posts


class PostsDeleteView(DeleteView):
    model = Posts
    success_url = reverse_lazy('blogem:all_posts')


class PostsUpdateView(UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blogem/posts_detail'
    form_class = PostsForm
    model = Posts


# @login_required
# def publish_post(request, pk):
#     post = get_object_or_404(Posts, pk=pk)
#     post.publish()
#     return redirect('blogem:posts_detail', pk=pk)


@login_required
def add_comment(request, pk):
    post = get_object_or_404(Posts, pk=pk)
    if request.method == 'POST':
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blogem:posts_detail', pk=post.pk)
    else:
        form = CommentsForm()
    return render(request, 'blogem/comment_form.html', {'form': form})


# @login_required
# def remove_comment(request, pk):

#     comment = get_object_or_404(Comments, pk=pk)
#     postpk = comment.post.pk
#     comment.delete()
#     return redirect('blogem:posts_details', pk=postpk)

blog/blogem/templates/accounts/login.html
{% extends 'blogem/base.html' %}
{% block content %}



<div class="jumbotron-fluid log">
    <h1>Login below Champ</h1> <br>
    {% if messages %}
<!-- <ul class="messages"> -->
    {% for message in messages %}
    <p {% if message.tags %} {% endif %}>
        {{ message }}
    </p>
    {% endfor %}
</ul>
{% endif %}
    <form action="{% url 'blogem:login' %}" method="POST">
        {%csrf_token%}

        <label for="username">Username</label> 
        <input type="text" name="username" placeholder="your username"><br><br>

        <label for="password">Password</label> 
        <input type="password" name="password" placeholder="your password"> <br><br>

        <input class="btn btn-light" type="submit" value="Login">
    </form>

</div>

{% endblock %}

blog/blogem/templates/accounts/register.html
{% extends 'blogem/base.html' %}
{% load bootstrap4 %}
{% block content %}

<div class="container"> 
<h1>Creating History eh ?</h1>
<h3>Register below</h3><br>
<form action="" method="POST">
    

    {% csrf_token %}
    
    {% bootstrap_form form %}
    <!-- {{form.errors}} -->
    <input class="btn btn-light" type="submit" value="Submit">
    
</form>
</div>






{% endblock %}

blog/blogem/templates/blogem/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    
    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/basic.css' %}">

    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@300&display=swap" rel="stylesheet">

    <title>Vlog'em ~ Blog'em</title>
</head>
<body>
    
    <nav class=" navbar navbar-expand-lg navbar-dark bg-transparent">
        <div class="container-fluid">
            <ul class="navbar-nav navbar-dark ">
                <li class="navbar-item"><a id="nv-items" class="nav-link navbar-brand" href="{% url 'blogem:home' %}">Home</a></li>
                <li class="navbar-item"><a id="nv-items" class="nav-link" href="{% url 'blogem:all_posts' %}">Blogs</a></li>

            </ul>
        </div>

        <div >
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="navbar-item"><a id="nav-name">Hey There ! {{ user.username|title }}</a></li>
                <li class="navbar-item"><a id="nv-items" class="nav-link" href="{% url 'blogem:create_post' %}">Create</a></li>
                <li class="navbar-item navbar-right"><a id="nv-items" class="nav-link" href="{% url 'blogem:logout' %}">Logout</a></li>
                {% else %}
                <li class="navbar-item navbar-right"><a id="nv-items" class="nav-link" href="{% url 'blogem:login' %}">Login</a></li>
                <li class="navbar-item"><a id="nv-items" class="nav-link" href="{% url 'blogem:register' %}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %} 
    {% endblock %}

</body>
</html>

blog/blogem/templates/blogem/comment_form.html
{% extends 'blogem/base.html' %}
{% load bootstrap4 %}
{% block content %}


<div class="container log1">
<h1>Comment here</h1>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-light" type="submit" value="Submit">
</form>
</div>




{% endblock %}

blog/blogem/templates/blogem/home.html
{% extends 'blogem/base.html' %}
{% block content %}

{% if user.is_authenticated %}
<div class="container-fluid">
<h1>Welcome Champ  <br> Nice to see you again! </h1>
{% else %}
<h1>Hey Champ! <br> You surfing or creating history ?</h1>
</div>
{% endif %}




{% endblock %}

blog/blogem/templates/blogem/posts_confirm_delete.html
{% extends 'blogem/base.html' %}
{% block content %}



<form method="post">
{% csrf_token %}
<h2>Sure u wanna delete {{object}} ?</h2>
<input class="btn btn-light" type="submit" value="Yes">
<a id="dl" class="btn btn-light"href="{% url 'blogem:posts_detail' pk=posts.pk %}">No</a>

</form>



{% endblock %}

blog/blogem/templates/blogem/posts_detail.html
{% extends 'blogem/base.html' %}
{% block content %}
<div class="container p1">
    <h1>{{posts.title}}</h1>

    <h5>By {{posts.user|title}}</h5>
    <p>{{posts.content|safe|linebreaks}}</p>
</div>
<div class="container">


{% if user.is_authenticated %}
    <h5><a class="btn btn-light" href="{% url 'blogem:update_post' pk=posts.pk %}"">Update</a></h5><br>
    <h5><a class="btn btn-light" href="{% url 'blogem:delete_post' pk=posts.pk %}"">Delete</a></h5>

    <hr>
    <h5><a class="btn btn-light" href="{% url 'blogem:create_comment' pk=posts.pk %}">Comment</a></h5><br>
    {% endif %}
    <h3>Check below for comments on this post </h3>
    {% for comment in posts.comments.all %}
    <br>
        {% if comment.count != 0 %}
            <p>User -> {{comment.user|title}}, commented</p>
            <p>{{comment.content}}</p>
        {% else %}
            <p>No one commented</p>
        {% endif %}
    
    {% endfor %}
</div>
{% endblock %}

blog/blogem/templates/blogem/posts_form.html
{% extends 'blogem/base.html' %}
{% load bootstrap4 %}
{% block content %}



<div class="container log1">
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-light" type="submit" value="Submit">
    </form>
</div>






{% endblock %}

blog/blogem/templates/blogem/posts_list.html
{% extends 'blogem/base.html' %}
{% block content %}



<div class="container p1">

    {% for post in posts_list %}
    <div>
        <h2><a id= "li" href="{% url 'blogem:posts_detail' pk=post.pk %}">{{post.title}}<br></a></h2>
        <p>Posted by {{post.user.username|title}}<br></a></p>
        <p>Total comments on this post: {{post.comments.count}}</a></p> <br><br>
    </div>
    
    {% endfor %}
</div>





{% endblock %}